# 基础
CONFIG_ZMK_KEYBOARD=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y

# 矩阵大小（你可以 later 修改）
CONFIG_ZMK_MATRIX_ROWS=4
CONFIG_ZMK_MATRIX_COLS=3

# 虚拟按键（编译不报错）
CONFIG_ZMK_KSCAN_SIMULATOR=y

# 低功耗（键盘端用）
CONFIG_ZMK_IDLE_TIMEOUT=3000
CONFIG_ZMK_SLEEP=y
